[package]
authors = ["Lucas Caro <lucascaro@gmail.com>"]
edition = "2018"
name = "snake"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston_window = "0.117.0"
rand = "0.8.2"
