version = 1
[game]
# Board size
block_size = 25
height = 25
width = 20

# Game settings
moving_period = 0.2
restart_time = 2.0
turbo_multiplier = 4.0

[colors]
board = [0.85, 0.82, 0.87, 1.0]
border = [0.06, 0.04, 0.04, 1.0]
food = [0.35, 0.74, 0.51, 1.0]
gameover = [0.91, 0.31, 0.22, 0.5]
snake = [0.21, 0.15, 0.65, 1.0]

[scores]
last = 68
top = [68]
